name: CI CD

on:
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # CI 서버로 코드 복사해오기 
      - name: Checkout Latest Repo
        uses: actions/checkout@main      
      # Docker buildx 설치 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 
      # docker 에 로그인 
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      # 이미지 빌드 하고 테스트하기
      - name: Build image
        shell: bash
        run: |
          docker build -t "${{ secrets.DOCKER_HUB_ID }}"/t1 -f ./frontend/Dockerfile.dev ./frontend
      - name: Test with built image
        shell: bash
        run: |
          docker run -e CI=true "${{ secrets.DOCKER_HUB_ID }}"/t1 npm run test

            
